version: '3.8'

services:

  we-client:
    image: wintang1103/we-client
    container_name: we_client
    ports:
      - "3000:3000"

  we-api:
    image: korroo/we-api
    container_name: we_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8068
      - DB_URL=${DB_URL}
      - JWT_VALID_AUDIENCE=${JWT_VALID_AUDIENCE}
      - JWT_VALID_ISSUER=${JWT_VALID_ISSUER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_UPLOAD_PRESET=${CLOUDINARY_UPLOAD_PRESET}
    ports:
      - "8068:8068"

  we-db:
    image: mcr.microsoft.com/mssql/server:2022-CU17-ubuntu-22.04
    container_name: we_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
    driver: local
